# This is a basic workflow that is manually triggered

name: Add User to Telegram Group

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [closed]

jobs:
  add_to_group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Required Fields
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Run Python Script
        run: |
          python script.py
